//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InviteCode
    {
        public int Id { get; set; }
        public int OrganizationID { get; set; }
        public string Code { get; set; }
        public bool IsExpired { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
        public int CreatedBy { get; set; }
        public string SentTo { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual User User { get; set; }
    }
}
