//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEvent
    {
        public int Id { get; set; }
        public string Details { get; set; }
        public System.DateTime Date { get; set; }
        public int EventType { get; set; }
        public int UserID { get; set; }
        public int OrganizationID { get; set; }
    
        public virtual LogEventType LogEventType { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual User User { get; set; }
    }
}
